//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module5.Premium.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public string Id { get; set; }
        public string Team1 { get; set; }
        public string Team2 { get; set; }
        public int State { get; set; }
        public int Score1 { get; set; }
        public int Score2 { get; set; }
        public int Period { get; set; }
        public string Timeouts1 { get; set; }
        public string Timeouts2 { get; set; }
    }
}
