//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module5.Premium.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchEvent
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public Nullable<int> TeamId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string MatchId { get; set; }
        public string Team1 { get; set; }
        public string Team2 { get; set; }
        public Nullable<int> PlayerId { get; set; }
    }
}
