//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module6.EventSourcing.Infrastructure.Persistence.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string RequestId { get; set; }
        public string Name { get; set; }
        public int CourtId { get; set; }
        public int StartingAt { get; set; }
        public int Length { get; set; }
        public string Notes { get; set; }
    
        public virtual Court Court { get; set; }
    }
}
