//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module6.EventSourcing.Infrastructure.Persistence.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        public Court()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int FirstSlot { get; set; }
        public int LastSlot { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
