//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module5.Deluxe.Infrastructure.Extras.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentEmail
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Body { get; set; }
        public System.DateTime Sent { get; set; }
    }
}
